# for wheel and imu fusion

frequency: 50
# sensor_timeout: 0.2
two_d_mode: true
transform_time_offset: 0.2
# transform_timeout: 0.8
print_diagnostics: true
publish_tf: true
# publish_acceleration: false

map_frame: map
odom_frame: odom
# base_link_frame: base_link
base_link_frame: base_footprint
# world_frame: odom

#odom0: wheel odometry
odom0: odom
odom0_config: [false, false, false,
               false, false, false,
               true , false, false,
               false, false, true,
               false, false, false]

#imu0
imu0: camera/imu
imu0_config: [false, false, false,
              false, false, true,
              false, false, false,
              false, false, true,
              false, false, false]
