shoulder_left_joint:
  ID: 0
  Return_Delay_Time: 0
  Operating_Mode: 3
  Profile_Acceleration: 0
  Profile_Velocity: 80
shoulder_right_joint:
  ID: 1
  Return_Delay_Time: 0
  Operating_Mode: 3
  Profile_Acceleration: 0
  Profile_Velocity: 80
elbow_joint:
  ID: 2
  Return_Delay_Time: 0
  Operating_Mode: 3
  Profile_Acceleration: 0
  Profile_Velocity: 40
wrist_joint:
  ID: 3
  Return_Delay_Time: 0
  Operating_Mode: 3
  Profile_Acceleration: 0
  Profile_Velocity: 60
endeffector_joint:
  ID: 4
  Return_Delay_Time: 0
  Operating_Mode: 5
  Profile_Acceleration: 0
  Profile_Velocity: 50
neck_joint:
  ID: 5
  Return_Delay_Time: 0
  Operating_Mode: 3
  Profile_Acceleration: 0
  Profile_Velocity: 30
